# bug_report.yml
name: バグ報告
description: 不具合報告はこちら
title: 'Bug: '
body:
  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: |
        不具合の概要を記載してください。
        見た目に関係する場合は、スクリーンショット等を貼り付けてください。
    validations:
      required: true
  - type: textarea
    id: process
    attributes:
      label: 再現手順
      description: 不具合を再現させる手順を記載してください。
      value: |
        1. 
        2. 
        3. 
        ...
    validations:
      required: true
  - type: textarea
    id: process
    attributes:
      label: 再現手順
      description: 不具合を再現させる手順を記載してください。
      value: |
        1. 
        2. 
        3. 
        ...
    validations:
      required: true
  - type: dropdown
    id: dropdown1
    attributes:
      label: 事象
      options:
        - 1:システムダウン
        - 2:異常終了
        - 3:データ破壊(ファイル、テーブル)
        - 4:データ更新誤り
        - 5:部分(一部機能障害)
        - 6:形式(メッセージ、データ等)
        - 7:その他
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: 再現環境
      description: |
        再現環境を記載してください。
        例：
        Chrome + Windows
        Edge + Windows
        Chrome + macOS
        Safari + macOS
    validations:
      required: true
  - type: textarea
    id: supplement
    attributes:
      label: 補足
